#!/bin/bash
gemfile_dirs=$(ls -d -- gemfiles/*)
echo $gemfile_dirs
for gemfile_dir in $gemfile_dirs
do
  gemfile="$gemfile_dir/Gemfile"
  echo
  echo "Testing with $gemfile..."
  export BUNDLE_GEMFILE=$gemfile
  bundle install
  ./test/run $gemfile_dir
  if [ $? -ne 0 ]
  then
    exit 1
  fi
done

